/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_admin;

import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import model.TxFdItem;

/**
 *
 * @author pphongsa
 */
public class PanelTxFdItem extends javax.swing.JPanel implements IxPanel, ActionListener, DocumentListener {
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form PanelTxFdItem
	 */
	public PanelTxFdItem() {
		initComponents();
		//
		docListener(txtSeq);
		docListener(txtNamePos);
		docListener(txtNameWeb);
		docListener(txtPrice);
		docListener(txtTax);
		docListener(taDesc);
	}
    
    private void docListener(javax.swing.JTextField cmp) {
        cmp.getDocument().putProperty("owner", cmp);
        cmp.getDocument().addDocumentListener(this);
    }
    
    private void docListener(javax.swing.JTextArea cmp) {
        cmp.getDocument().putProperty("owner", cmp);
        cmp.getDocument().addDocumentListener(this);
    }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        lbSeq = new JLabel();
        txtSeq = new JTextField();
        lbNamePos = new JLabel();
        txtNamePos = new JTextField();
        lbNameWeb = new JLabel();
        txtNameWeb = new JTextField();
        lbPrice = new JLabel();
        txtPrice = new JTextField();
        lbTax = new JLabel();
        txtTax = new JTextField();
        cxBypass = new JCheckBox();
        cxWeb = new JCheckBox();
        scp1 = new JScrollPane(
    		JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, 
    		JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        taDesc = new JTextArea();
        lbDesc = new JLabel();

        lbSeq.setText("Seq");

        txtSeq.setHorizontalAlignment(JTextField.TRAILING);
        txtSeq.setText("0");

        lbNamePos.setText("Item Name (POS)");

        lbNameWeb.setText("Item Name (Web)");

        lbPrice.setText("Price");

        txtPrice.setHorizontalAlignment(JTextField.TRAILING);
        txtPrice.setText("0.00");

        lbTax.setText("Tax");

        txtTax.setHorizontalAlignment(JTextField.TRAILING);
        txtTax.setText("0.00");

        cxBypass.setText("Bypass Options");
        cxBypass.setBorder(null);
        cxBypass.setActionCommand("update_bypass");
        cxBypass.addActionListener(this);

        cxWeb.setText("Web");
        cxWeb.setBorder(null);
        cxWeb.setEnabled(false);

        taDesc.setTabSize(0);
        taDesc.setMargin(new Insets(3, 3, 3, 3));
        scp1.setViewportView(taDesc);

        lbDesc.setText("Web Description");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPrice)
                    .addComponent(lbNameWeb)
                    .addComponent(lbNamePos)
                    .addComponent(lbSeq)
                    .addComponent(lbDesc))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxBypass)
                        .addGap(18, 18, 18)
                        .addComponent(cxWeb))
                    .addComponent(txtSeq, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamePos, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameWeb, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPrice, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTax)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTax, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                    .addComponent(scp1, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeq)
                    .addComponent(txtSeq, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamePos)
                    .addComponent(txtNamePos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNameWeb)
                    .addComponent(txtNameWeb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrice)
                    .addComponent(txtPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTax)
                    .addComponent(txtTax, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cxBypass)
                    .addComponent(cxWeb))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(scp1, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDesc)))
        );
    }//GEN-END:initComponents
	
	private void _updateObject(Object srcObj) {
		if (!updFlg) return;

		if (srcObj instanceof javax.swing.JTextArea) {
			fdItm.setItmDesc(taDesc.getText().trim());
			return;
		}
		
		javax.swing.JTextField srcFld = (javax.swing.JTextField)srcObj;
		
		if (txtSeq == srcFld) {
			try {
				int num1 = Integer.parseInt(txtSeq.getText());
				fdItm.setItmSeq(num1);
			} catch (Exception e) {}
		}
		if (txtNamePos == srcFld) {
			fdItm.setItmNamePos(txtNamePos.getText().trim());
		}
		if (txtNameWeb == srcFld) {
			fdItm.setItmNameWeb(txtNameWeb.getText().trim());
		}
		if (txtPrice == srcFld) {
			try {
				double val1 = Double.parseDouble(txtPrice.getText());
				fdItm.setItmPrice(val1);
			} catch (Exception e) {}
		}
		if (txtTax == srcFld) {
			try {
				double val1 = Double.parseDouble(txtTax.getText());
				fdItm.setItmTax(val1);
			} catch (Exception e) {}
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox cxBypass;
    private JCheckBox cxWeb;
    private JLabel lbDesc;
    private JLabel lbNamePos;
    private JLabel lbNameWeb;
    private JLabel lbPrice;
    private JLabel lbSeq;
    private JLabel lbTax;
    private JScrollPane scp1;
    private JTextArea taDesc;
    private JTextField txtNamePos;
    private JTextField txtNameWeb;
    private JTextField txtPrice;
    private JTextField txtSeq;
    private JTextField txtTax;
    // End of variables declaration//GEN-END:variables
    
    private TxFdItem fdItm = null;
    private boolean updFlg = false;
    
	@Override
	public JPanel getPanel() {
		return this;
	}

	@Override
	public boolean isDataValid() {
		try {
			Integer.parseInt(txtSeq.getText().trim());
			Double.parseDouble(txtPrice.getText().trim());
			Double.parseDouble(txtTax.getText().trim());
		} catch (Exception e) {
			return false;
		}
		return !txtNamePos.getText().trim().isEmpty();
	}

	@Override
	public Object getObject() {
		return fdItm;
	}

	@Override
	public void setObject(Object obj) {
		fdItm = null;
		if (null != obj) { 
			fdItm = (TxFdItem)obj;
		}
		updFlg = false;
		//
		txtSeq.setText(null==obj?"0":String.format("%d",fdItm.getItmSeq()));
		txtNamePos.setText(null==obj?"":fdItm.getItmNamePos());
		txtNameWeb.setText(null==obj?"":fdItm.getItmNameWeb());
		txtPrice.setText(null==obj?"0.00":String.format("%.2f", fdItm.getItmPrice()));
		txtTax.setText(null==obj?"0.00":String.format("%.2f", fdItm.getItmTax()));
		taDesc.setText(null==obj?"":fdItm.getItmDesc());
		cxBypass.setSelected(null==obj?false:fdItm.isBypassOpt());
		//
		txtSeq.setEnabled(null!=obj);
		txtNamePos.setEnabled(null!=obj);
		txtNameWeb.setEnabled(null!=obj);
		txtPrice.setEnabled(null!=obj);
		txtTax.setEnabled(null!=obj);
		taDesc.setEnabled(null!=obj);
		cxBypass.setEnabled(null!=obj);
		//
		updFlg = null != fdItm;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if (!updFlg) return;
		//
		String cmd = e.getActionCommand();
		if ("update_bypass".equals(cmd)) {
			fdItm.setItmBypassOpt(cxBypass.isSelected());
		}
	}

	@Override
	public void insertUpdate(DocumentEvent de) {
		_updateObject(de.getDocument().getProperty("owner"));
	}
	@Override
	public void removeUpdate(DocumentEvent de) {
		_updateObject(de.getDocument().getProperty("owner"));
	}
	@Override
	public void changedUpdate(DocumentEvent de) {
		_updateObject(de.getDocument().getProperty("owner"));
	}
}
