/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_admin;

import java.awt.Frame;
import java.sql.SQLException;

import javax.swing.JPanel;

import model.TxPrinter;

/**
 *
 * @author pphongsa
 */
public class PanelTxPrinter extends javax.swing.JPanel implements IxPanel {

    /**
     * Creates new form PanelTxPrinter
     */
    public PanelTxPrinter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIP = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cxBuzzer = new javax.swing.JCheckBox();

        lbIP.setText("Printer IP");

        lbName.setText("Printer Name");

        cxBuzzer.setText("Buzzer");
        cxBuzzer.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbName)
                    .addComponent(lbIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxBuzzer)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIP)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cxBuzzer))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cxBuzzer;
    private javax.swing.JLabel lbIP;
    private javax.swing.JLabel lbName;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    
    private TxPrinter prn1 = null;
    
	@Override
	public JPanel getPanel() {
		return this;
	}

	@Override
	public boolean isDataValid() {
		return !(null==prn1 
			|| txtIP.getText().isEmpty() 
			|| txtName.getText().isEmpty());
	}

	@Override
	public Object getObject() {
		return prn1;
	}

	@Override
	public void setObject(Object obj) {
		prn1 = null;
		if (null != obj) {
			prn1 = (TxPrinter)obj;
		}
		//
		cxBuzzer.setSelected(null==prn1?false:prn1.hasBuzzer());
		txtIP.setText(null==prn1?"":prn1.getPrnIp());
		txtName.setText(null==prn1?"":prn1.getPrnName());
		//
		cxBuzzer.setEnabled(null!=prn1);
		txtIP.setEnabled(null!=prn1);
		txtName.setEnabled(null!=prn1);
	}

	public boolean saveObject() throws SQLException {
		if (!isDataValid()) return false;
		//
		prn1.setPrnIp(txtIP.getText());
		prn1.setPrnName(txtName.getText());
		prn1.setBuzzer(cxBuzzer.isSelected());
		prn1.save();
		//
		return true;
	}

	public void deleteObject() throws SQLException {
		if (null == prn1) return;
		prn1.delete();
	}
}
