/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_admin;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

import model.TxFdCat;

/**
 *
 * @author pphongsa
 */
public class PanelTxFdCat extends javax.swing.JPanel implements IxPanel, ActionListener {
	
	private Frame prFrm;

	/**
	 * Creates new form PanelTxFdCat
	 */
	public PanelTxFdCat(Frame _pr) {
		initComponents();
		prFrm = _pr;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        lbSeq = new JLabel();
        txtSeq = new JTextField();
        lbNamePos = new JLabel();
        txtNamePos = new JTextField();
        lbNameWeb = new JLabel();
        txtNameWeb = new JTextField();
        lb1 = new JLabel();
        btBgColor = new JButton();
        
        lbBgColor = new JLabel();
        lbBgColor.setOpaque(true);
        
        lbDesc = new JLabel();
        scp1 = new JScrollPane(
    		JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, 
    		JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        taDesc = new JTextArea();
        cxWeb = new JCheckBox();

        lbSeq.setText("Seq");

        txtSeq.setHorizontalAlignment(JTextField.TRAILING);
        txtSeq.setText("0");

        lbNamePos.setText("Cat Name (POS)");

        lbNameWeb.setText("Cat Name (Web)");

        lb1.setText("BG Color");

        btBgColor.setText("BG Color");
        btBgColor.setActionCommand("bt_bg_color");
        btBgColor.addActionListener(this);

        lbBgColor.setText("<Bg Color>");

        lbDesc.setText("Web Description");

        taDesc.setTabSize(0);
        taDesc.setMargin(new Insets(3, 3, 3, 3));
        scp1.setViewportView(taDesc);

        cxWeb.setText("Web");
        cxWeb.setBorder(null);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNameWeb)
                    .addComponent(lbNamePos)
                    .addComponent(lbSeq)
                    .addComponent(lbDesc)
                    .addComponent(lb1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(cxWeb)
                    .addComponent(txtNamePos, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeq, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameWeb, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBgColor)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBgColor))
                    .addComponent(scp1, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeq)
                    .addComponent(txtSeq, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamePos)
                    .addComponent(txtNamePos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNameWeb)
                    .addComponent(txtNameWeb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(btBgColor)
                    .addComponent(lbBgColor))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cxWeb)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbDesc)
                    .addComponent(scp1, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)))
        );
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btBgColor;
    private JCheckBox cxWeb;
    private JLabel lb1;
    private JLabel lbBgColor;
    private JLabel lbDesc;
    private JLabel lbNamePos;
    private JLabel lbNameWeb;
    private JLabel lbSeq;
    private JScrollPane scp1;
    private JTextArea taDesc;
    private JTextField txtNamePos;
    private JTextField txtNameWeb;
    private JTextField txtSeq;
    // End of variables declaration//GEN-END:variables
    
    private boolean updFlg = false;

	@Override
	public JPanel getPanel() {
		return this;
	}

	@Override
	public boolean isDataValid() {
		try {
			Integer.parseInt(txtSeq.getText().trim());
		} catch (Exception e) {
			return false;
		}
		return !txtNamePos.getText().trim().isEmpty();
	}

	@Override
	public Object getObject() {
		return null;
	}

	@Override
	public void setObject(Object obj) {
		TxFdCat cat1 = null;
		if (null != obj) { 
			cat1 = (TxFdCat)obj;
		}
		//
		txtSeq.setText(null==cat1?"0":String.format("%d", cat1.getCatSeq()));
		txtNamePos.setText(null==cat1?"":cat1.getCatNamePos());
		txtNameWeb.setText(null==cat1?"":cat1.getCatNameWeb());
		taDesc.setText(null==cat1?"":cat1.getCatDesc());
		lbBgColor.setText(null==cat1?"-default-":cat1.getCatBgColor().toString());
		lbBgColor.setBackground(null==cat1?Color.GRAY:cat1.getCatBgColor());
		//
		txtSeq.setEnabled(null!=cat1);
		txtNamePos.setEnabled(null!=cat1);
		txtNameWeb.setEnabled(null!=cat1);
		taDesc.setEnabled(null!=cat1);
		btBgColor.setEnabled(null!=cat1);
		//
		updFlg = null!=cat1;
	}
	
	void updateObject(TxFdCat cat1) {
		try {
			int num1 = Integer.parseInt(txtSeq.getText().trim());
			cat1.setCatSeq(num1);
		} catch (Exception e) {}
		cat1.setCatNamePos(txtNamePos.getText().trim());
		cat1.setCatNameWeb(txtNameWeb.getText().trim());
		cat1.setCatDesc(taDesc.getText().trim());
		cat1.setCatBgColor(lbBgColor.getBackground());
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if (!updFlg) return;
		//
		String cmd = e.getActionCommand();
		if ("bt_bg_color".equals(cmd)) {
			Color scol = JColorChooser.showDialog(
				prFrm, "Background Color", lbBgColor.getBackground());
			if (null != scol) {
				lbBgColor.setBackground(scol);
			}
		}
	}
}
