/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_admin;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

import model.TxOpt;
import refx.OptionType;

/**
 *
 * @author pphongsa
 */
public class PanelTxOpt extends javax.swing.JPanel implements IxPanel {

    /**
     * Creates new form PanelTxOpt
     */
    public PanelTxOpt() {
        initComponents();
        //
        DefaultComboBoxModel<OptionType> def1 = new DefaultComboBoxModel<>();
        OptionType[] otypes = OptionType.values();
        for (OptionType opt1 : otypes) {
        	def1.addElement(opt1);
        }
        cmbType.setModel(def1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSeq = new javax.swing.JLabel();
        txtSeq = new javax.swing.JTextField();
        lbNamePos = new javax.swing.JLabel();
        txtNamePos = new javax.swing.JTextField();
        lbNameWeb = new javax.swing.JLabel();
        txtNameWeb = new javax.swing.JTextField();
        lbType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        cxMand = new javax.swing.JCheckBox();
        lbCmnt = new javax.swing.JLabel();
        txtCmnt = new javax.swing.JTextField();

        lbSeq.setText("Seq");

        txtSeq.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSeq.setText("0");

        lbNamePos.setText("Option Name (POS)");

        lbNameWeb.setText("Option Name (Web)");

        lbType.setText("Type");

        cxMand.setText("Mandatory");
        cxMand.setBorder(null);

        lbCmnt.setText("Comment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCmnt)
                    .addComponent(lbType)
                    .addComponent(lbNameWeb)
                    .addComponent(lbNamePos)
                    .addComponent(lbSeq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxMand)
                    .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamePos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmnt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeq)
                    .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamePos)
                    .addComponent(txtNamePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNameWeb)
                    .addComponent(txtNameWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cxMand)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCmnt)
                    .addComponent(txtCmnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<OptionType> cmbType;
    private javax.swing.JCheckBox cxMand;
    private javax.swing.JLabel lbCmnt;
    private javax.swing.JLabel lbNamePos;
    private javax.swing.JLabel lbNameWeb;
    private javax.swing.JLabel lbSeq;
    private javax.swing.JLabel lbType;
    private javax.swing.JTextField txtCmnt;
    private javax.swing.JTextField txtNamePos;
    private javax.swing.JTextField txtNameWeb;
    private javax.swing.JTextField txtSeq;
    // End of variables declaration//GEN-END:variables

	@Override
	public JPanel getPanel() {
		return this;
	}

	@Override
	public boolean isDataValid() {
		try {
			int seq1 = Integer.parseInt(txtSeq.getText());
			//System.out.printf("seq[%d]\nname[%s]\n", seq1, txtNamePos.getText());
			return seq1>0 && !txtNamePos.getText().trim().isEmpty();
		} catch (Exception e) {
			// invalid number format
			e.printStackTrace();
		}
		return false;
	}

	@Override
	public Object getObject() {
		return null;
	}
	
	public void updateObject(TxOpt opt1) {
		opt1.setOptSeq(Integer.parseInt(txtSeq.getText()));
		opt1.setOptNamePos(txtNamePos.getText());
		opt1.setOptNameWeb(txtNameWeb.getText());
		opt1.setOptType((OptionType)cmbType.getSelectedItem());
		opt1.setOptMand(cxMand.isSelected());
		opt1.setOptComment(txtCmnt.getText().trim());
	}

	@Override
	public void setObject(Object obj) {
		TxOpt opt = null;
		if (null != obj) {
			opt = (TxOpt)obj;
		}
		cmbType.setSelectedItem(null==opt?OptionType.Single:opt.getOptType());
		cxMand.setSelected(null==opt?false:opt.isMandatory());
		txtCmnt.setText(null==opt?"":opt.getOptComment());
		txtNamePos.setText(null==opt?"":opt.getOptNamePos());
		txtNameWeb.setText(null==opt?"":opt.getOptNameWeb());
		txtSeq.setText(null==opt?"":String.format("%d", opt.getOptSeq()));
		//
		cmbType.setEnabled(null!=opt);
		cxMand.setEnabled(null!=opt);
		txtCmnt.setEnabled(null!=opt);
		txtNamePos.setEnabled(null!=opt);
		txtNameWeb.setEnabled(null!=opt);
		txtSeq.setEnabled(null!=opt);
	}
}
