/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import model.TxOptItem;

/**
 *
 * @author pphongsa
 */
public class PanelTxOptItem extends javax.swing.JPanel implements IxPanel, ActionListener, DocumentListener {
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form PanelTxOptItem
     */
    public PanelTxOptItem() {
        initComponents();
        //
        docListener(txtNamePos);
        docListener(txtNameWeb);
        docListener(txtPrice);
        docListener(txtSeq);
    }
    
    private void docListener(javax.swing.JTextField cmp) {
        cmp.getDocument().putProperty("owner", cmp);
        cmp.getDocument().addDocumentListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSeq = new javax.swing.JLabel();
        txtSeq = new javax.swing.JTextField();
        lbNamePos = new javax.swing.JLabel();
        txtNamePos = new javax.swing.JTextField();
        lbNameWeb = new javax.swing.JLabel();
        txtNameWeb = new javax.swing.JTextField();
        lbPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        cxDefault = new javax.swing.JCheckBox();
        cxDefault.setActionCommand("update_default");
        cxDefault.addActionListener(this);

        lbSeq.setText("Seq");
        lbSeq.setToolTipText("");

        txtSeq.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSeq.setText("0");

        lbNamePos.setText("Name (Pos)");

        lbNameWeb.setText("Name (Web)");

        lbPrice.setText("Price");

        txtPrice.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPrice.setText("0.00");

        cxDefault.setText("Default Item");
        cxDefault.setToolTipText("");
        cxDefault.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPrice)
                    .addComponent(lbNameWeb)
                    .addComponent(lbNamePos)
                    .addComponent(lbSeq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxDefault)
                    .addComponent(txtNamePos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeq)
                    .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamePos)
                    .addComponent(txtNamePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNameWeb)
                    .addComponent(txtNameWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cxDefault))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cxDefault;
    private javax.swing.JLabel lbNamePos;
    private javax.swing.JLabel lbNameWeb;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbSeq;
    private javax.swing.JTextField txtNamePos;
    private javax.swing.JTextField txtNameWeb;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeq;
    // End of variables declaration//GEN-END:variables
    
    private TxOptItem opi1;
    private boolean updFlg = false;
    private IxOpi opiLst;

	private void _updateObject(DocumentEvent de) {
		if (!updFlg) return;
		if (null == opi1) return;
		//
		javax.swing.JTextField srcFld = 
			(javax.swing.JTextField)de.getDocument().getProperty("owner");
		if (txtSeq == srcFld) {
			try {
				int num1 = Integer.parseInt(txtSeq.getText());
				opi1.setOpiSeq(num1);
			} catch (Exception e) {}
		}
		if (txtPrice == srcFld) {
			try {
				double val1 = Double.parseDouble(txtPrice.getText());
				opi1.setOpiPrice(val1);
			} catch (Exception e) {}
		}
		if (txtNamePos == srcFld) {
			opi1.setOpiNamePos(txtNamePos.getText());
		}
		if (txtNameWeb == srcFld) {
			opi1.setOpiNameWeb(txtNameWeb.getText());
		}
	}
    
    //
	
	void setOpiLst(IxOpi _lst) {
		opiLst = _lst;
	}
    
	@Override
	public JPanel getPanel() {
		return this;
	}

	@Override
	public boolean isDataValid() {
		return !txtNamePos.getText().trim().isEmpty();
	}

	@Override
	public Object getObject() {
		return opi1;
	}

	@Override
	public void setObject(Object obj) {
		updFlg = false;
		opi1 = null;
		if (null != obj) {
			opi1 = (TxOptItem)obj;
		}
		//
		cxDefault.setSelected(null==opi1?false:opi1.isOpiDefault());
		txtNamePos.setText(null==opi1?"":opi1.getOpiNamePos());
		txtNameWeb.setText(null==opi1?"":opi1.getOpiNameWeb());
		txtPrice.setText(null==opi1?"0.00":String.format("%.2f", opi1.getOpiPrice()));
		txtSeq.setText(null==opi1?"0":String.format("%d", opi1.getOpiSeq()));
		//
		cxDefault.setEnabled(null!=opi1);
		txtNamePos.setEnabled(null!=opi1);
		txtNameWeb.setEnabled(null!=opi1);
		txtPrice.setEnabled(null!=opi1);
		txtSeq.setEnabled(null!=opi1);
		//
		updFlg = null != opi1;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if (null == opi1) return;
		//
		String cmd = e.getActionCommand();
		if ("update_default".equals(cmd)) {
			opi1.setOpiDefault(cxDefault.isSelected());
			if (null != opiLst) {
				opiLst.defaultChangeTo(opi1);
			}
		}
	}

	@Override
	public void insertUpdate(DocumentEvent e) {
		_updateObject(e);
	}
	@Override
	public void removeUpdate(DocumentEvent e) {
		_updateObject(e);
	}
	@Override
	public void changedUpdate(DocumentEvent e) {
		_updateObject(e);
	}
}
