/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_admin;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

import model.TxUser;
import refx.UserGroup;

/**
 *
 * @author pphongsa
 */
public class PanelTxUser extends javax.swing.JPanel implements IxPanel {

    /**
     * Creates new form PanelTxUser
     */
    public PanelTxUser() {
        initComponents();
        //
        DefaultComboBoxModel<UserGroup> def1 = new DefaultComboBoxModel<>();
        UserGroup[] ugrps = UserGroup.values();
        for (UserGroup ugrp1 : ugrps) {
        	def1.addElement(ugrp1);
        }
        cbUsrGrp.setModel(def1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbPass = new javax.swing.JLabel();
        txtPosPwd = new javax.swing.JTextField();
        lbUsrGrp = new javax.swing.JLabel();
        cbUsrGrp = new javax.swing.JComboBox<>();

        lbName.setText("Name");
        lbPass.setText("POS Pass Code");
        lbUsrGrp.setText("Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbUsrGrp)
                    .addComponent(lbPass)
                    .addComponent(lbName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUsrGrp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPass)
                    .addComponent(txtPosPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsrGrp)
                    .addComponent(cbUsrGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<UserGroup> cbUsrGrp;
    private javax.swing.JLabel lbUsrGrp;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPass;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosPwd;
    // End of variables declaration//GEN-END:variables
    
    //private boolean updFlg = false;

	@Override
	public JPanel getPanel() {
		return this;
	}

	@Override
	public boolean isDataValid() {
		return !txtName.getText().trim().isEmpty();
	}

	@Override
	public Object getObject() {
		return null;
	}

	@Override
	public void setObject(Object obj) {
		TxUser usrObj = null;
		if (null != obj) {
			usrObj = (TxUser)obj;
		}
		//
		txtName.setText(null==usrObj?"":usrObj.getUsrName());
		txtPosPwd.setText(null==usrObj?"":usrObj.getUsrPosPWD());
		cbUsrGrp.setSelectedItem(null==usrObj?UserGroup.Waiter:usrObj.getUsrGrp());
		//
		txtName.setEnabled(null!=usrObj);
		txtPosPwd.setEnabled(null!=usrObj);
		cbUsrGrp.setEnabled(null!=usrObj);
		//
		this.updateUI();
	}

	public void updateObject(TxUser usr1) {
		usr1.setUsrGrp((UserGroup)cbUsrGrp.getSelectedItem());
		usr1.setUsrName(txtName.getText().trim());
		usr1.setUsrPosPWD(txtPosPwd.getText().trim());
	}
}
